# Algoritma KNN



**Import Library**

---
import library yang akan digunakan





In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
import sklearn.metrics as metrics
from sklearn.metrics import classification_report
from sklearn.model_selection import KFold, cross_validate
from sklearn.model_selection import cross_val_score
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns



**Import Dataset**

---
Data yang telah didapat setelah dilakukan rekap data secara manual dan akan dilakukan pembersihan data serta penambahan fitur yang akan dibutuhkan.

In [3]:
df=pd.read_excel('dataseimbangbener.xlsx')
df

SEX  UMUR    TB      TB/U  sangat_pendek  pendek  label
0       1    55  97.0 -2.323074              0       1      1
1       1    51  96.1 -2.096405              0       1      1
2       2    49  92.0 -2.661017              0       1      1
3       1    37  86.5 -2.855393              0       1      1
4       1    34  84.3 -2.936088              0       1      1
...   ...   ...   ...       ...            ...     ...    ...
7800    1    40  95.4 -0.921263              0       0      0
7801    1    35  90.1 -1.503828              0       0      0
7802    2    35  88.1 -1.706878              0       0      0
7803    1    33  96.1  0.503251              0       0      0
7804    1    25  86.0 -0.868616              0       0      0

[7805 rows x 7 columns]

In [4]:
df.drop(["sangat_pendek","pendek","TB/U"],axis=1,inplace=True)
df

SEX  UMUR    TB  label
0       1    55  97.0      1
1       1    51  96.1      1
2       2    49  92.0      1
3       1    37  86.5      1
4       1    34  84.3      1
...   ...   ...   ...    ...
7800    1    40  95.4      0
7801    1    35  90.1      0
7802    2    35  88.1      0
7803    1    33  96.1      0
7804    1    25  86.0      0

[7805 rows x 4 columns]

In [5]:
#pisahkan data feature dan target
X = df.iloc [:, : -1]    #sekumpulan feature untuk training dataset
y = df.iloc [:,-1: ].values.ravel()             #sekumpulan nilai target untuk training set

# X.head()
X.values

array([[ 1. , 55. , 97. ],
       [ 1. , 51. , 96.1],
       [ 2. , 49. , 92. ],
       ...,
       [ 2. , 35. , 88.1],
       [ 1. , 33. , 96.1],
       [ 1. , 25. , 86. ]])

In [6]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [8]:
X_train.shape  #data training 80%


(6244, 3)

In [9]:
X_test.shape #data test 20%

(1561, 3)

In [10]:
# y_train.shape

In [11]:
# y_test.shape

In [27]:
# model learning data dengan dengan knn
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=3, p=2) # k=3
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

Predict

---



In [22]:
#hasil prediksi

y_pred = classifier.predict(X_test) # yang diprediski dari data test
print("classification:")
print(classification_report(y_test,y_pred))
print("confusion:")
print(confusion_matrix(y_test,y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", metrics.precision_score(y_test, y_pred))
print("Recall:", metrics.recall_score(y_test, y_pred))

classification:
              precision    recall  f1-score   support

           0       0.98      0.96      0.97       807
           1       0.96      0.98      0.97       754

    accuracy                           0.97      1561
   macro avg       0.97      0.97      0.97      1561
weighted avg       0.97      0.97      0.97      1561

confusion:
[[778  29]
 [ 12 742]]
Accuracy: 0.9737347853939782
Precision: 0.9623865110246433
Recall: 0.9840848806366048


In [23]:
cols = {
    'Y True' : y_test,
    'predic' : y_pred,
    
}
print("Prediksi yang dihasilkan")
pd.DataFrame(cols)

Prediksi yang dihasilkan


Y True  predic
0          1       1
1          1       1
2          0       0
3          1       1
4          0       0
...      ...     ...
1556       1       1
1557       1       1
1558       1       1
1559       1       1
1560       0       0

[1561 rows x 2 columns]

In [24]:
# y_pred 

In [25]:
classifier.predict([[1,55,97]])

array([1], dtype=int64)

In [17]:
# y_predk = classifier.predict([[1, 32, 82.7, -3.153154]])
# y_pred

Pengukuran peformance


In [18]:
kfold = KFold(n_splits=10)
scores = ['accuracy', 'precision', 'recall']
results = cross_validate(classifier, X_test, y_test, cv=kfold, scoring=scores, return_train_score=True)
results_data = pd.DataFrame(results)
results_data

fit_time  score_time  test_accuracy  train_accuracy  test_precision  \
0  0.004986    0.009976       0.980892        0.980769        1.000000   
1  0.003989    0.007979       0.967949        0.979359        0.928571   
2  0.002992    0.010967       0.935897        0.983630        0.917647   
3  0.003989    0.006983       0.967949        0.980071        0.975000   
4  0.002993    0.006945       0.967949        0.983630        0.951807   
5  0.003989    0.006984       0.948718        0.981495        0.945205   
6  0.003987    0.007976       0.974359        0.981495        0.976190   
7  0.003949    0.008019       0.948718        0.980783        0.918919   
8  0.002992    0.007979       0.948718        0.985053        0.915493   
9  0.003989    0.007978       0.980769        0.979359        0.971429   

   train_precision  test_recall  train_recall  
0         0.970717     0.964286      0.989552  
1         0.967422     1.000000      0.991292  
2         0.975146     0.962963      0.991085  
3         0.969432     0.962963      0.989599  
4         0.972424     0.987500      0.994065  
5         0.968526     0.945205      0.994126  
6         0.969388     0.976190      0.992537  
7         0.971306     0.971429      0.989766  
8         0.978448     0.970149      0.991266  
9         0.968571     0.985507      0.989781

In [19]:
print("Preformance Model KNN")

accuracy = results_data.test_accuracy.mean() 
precision = results_data.test_precision.mean() 
recall = results_data.test_recall.mean() 

print("Accuracy : %0.2f" % accuracy)
print("Precision : %0.2f " % precision)
print("Recall : %0.2f " % recall)

Preformance Model KNN
Accuracy : 0.96
Precision : 0.95 
Recall : 0.97 


In [20]:
import pickle
pickle.dump(classifier, open('knn.pkl','wb'))